package ar.com.intrale.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import io.micronaut.core.util.StringUtils;

@DynamoDBTable(tableName="product")
public class Product {

	@DynamoDBHashKey(attributeName="productId")
	@DynamoDBAutoGeneratedKey
	private String id;
	private String businessName;

	private String category;
	
	private String name;
	private String description;
	private Price price;

	private Long stock;

	public String getBusinessName() {
		return businessName;
	}
	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		if (StringUtils.isNotEmpty(id)) {
			this.id = id;
		}
	}
	public String getName() {
		return name;
	}
	public void setName(String title) {
		this.name = title;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Long getStock() {
		return stock;
	}
	public void setStock(Long stock) {
		this.stock = stock;
	}
	public Price getPrice() {
		return price;
	}
	public void setPrice(Price price) {
		this.price = price;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	
	
	
}
