app: 
  name: IntraleFunction
  microservices: false
  instantiate:
    factory: true
    provider: true
    create: true
    delete: true
    read: true
    update: true
  security:
    create: adminProducts
    delete: adminProducts
    read: adminProducts
    update: adminProducts
  activity:
    enabled: ${validate.enabled:false}
    maxInactivity: 60000
    fixedDelay: 30s
    initialDelay: 15s
  aws:
    region: us-east-2
  cognito:
    clientId: 1ve1nokbjnmhk1adiben0a9iao
    userPoolId: us-east-2_rLbLF8HCb
    access: ${cognito.access}
    secret: ${cognito.secret}
    connectionTimeout: 2000
    readTimeout: 2000
    urlPrefix: https://cognito-idp.
    urlMid: .amazonaws.com/
    urlSufix: /.well-known/jwks.json    
  database:
    access: ${database.access}
    secret: ${database.secret}
micronaut:
    http:
        client:
            read-timeout: 30s