app: 
  name: IntraleFunction
  microservices: false
  instantiate:
    factory: true
    provider: true
    create: true
    delete: true
    read: true
    update: true
  security:
    create: adminProducts
    delete: adminProducts
    read: adminProducts
    update: adminProducts
  activity:
    enabled: ${validate.enabled:false}
    maxInactivity: 60000
    fixedDelay: 30s
    initialDelay: 15s
  aws:
    region: us-east-2
  database:
    access: ${database.access}
    secret: ${database.secret}
micronaut:
    http:
        client:
            read-timeout: 30s